---
title: "CV"
date: today
---

### Contact

-   Address: 1-31 Machikaneyama Toyonaka, Osaka, 560-0043 Japan
-   Phone: 81-(0)6-6850-5633
-   Email: matsubayashi at osipp.osaka-u.ac.jp

### Employment

-   2020- Professor, Osaka School of International Public Policy, Osaka University
-   2013-2020 Associate Professor, Osaka School of International Public Policy, Osaka University
-   2007-2013 Assistant Professor in Political Science, University of North Texas (tenured, May 2013)

### Education

-   2007 Ph.D. in Political Science, Texas A¥&M University, US
-   2002 M.A. in American Studies, Doshisha University, Japan
-   2000 B.A. in Law, Doshisha University, Japan

### Research and Teaching Fields

-   Political Behavior
-   Political Representation
-   Public Health

### Award

-   Osaka University Prize (2019).
-   JSPS (Japan Society for the Promotion of Science) Prize (2019).
-   The Best Paper Award for "Tohyo Kankyo to Tohyo Ritsu (Polling Stations and Voter Turnout), Japanese Association of Electoral Studies (2017).
-   Nikkei Keizai Bunka Tosho Sho (The Nikkei Award for Books on Economy) for *Jisatu no nai Shakai he* (2013).
-   The Best Paper Award for "Shichoson Gikai ni okeru Josei no Sannyu (Female Candidates and Municipal Elections in Japan)," Japanese Association of Electoral Studies (2012).
-   Warren E. Miller Award to attend the 2005 ICPSR Summer Program.
-   The Pi Sigma Alpha Award for the best paper presented at the 2004 Annual Meeting of the Southwestern Political Science Association for "Size of Democracy and Support for the Political System" (2005).

### Peer-reviewed Publications in Political Science and Economics

<ol reversed>

<li>Tetsuya Matsubayashi. 2023. "Senkyo Seido Kaikaku to Chiho Toshino Tohyouritusa no Shukusho (Consequences of Electoral Reform for Rural-Urban Differences in Voter Turnout)." *Nenpo Seijigaku (Annuals of Japanese Political Science Association)*</li>

<li>Masataka Harada and Tetsuya Matsubayashi. 2023. "Intergovernmental Transfers as Magnets for Low-Income People." *Applied Economics Letters*.</li>

<li>Shuhei Kitamura and Tetsuya Matsubayashi. 2022. "Now or Later?: The Inter-temporal Decision-Making of Electoral Participation." *Political Behavior*.</li>

<li>Tetsuya Matsubayashi and Shiro Sakaiya. 2021. "Income Inequality and Income Bias in Voter Turnout." *European Journal of Political Economy* 66.</li>

<li>Tetsuya Matsubayashi and Kelan Lu. 2019. "Age and Turnout in Aging Societies." *International Journal of Public Opinion Research* (receiving financial support from Japan Center for Economic Research).</li>

<li>Tetsuya Matsubayashi. 2018. "Kijituzen Touhyo Seido to Tohyoritsu (Early Voting and Voter Turnout)." *Senkyo Kenkyu (Japanese Journal of Electoral Studies)* 33(2): 58-72 (receiving financial support from Japan Center for Economic Research).</li>

<li>Yasushi Asako and Tetsuya Matsubayashi. 2016. "Business Cycle and the Entry of Third-party Candidates in the US State-level Elections." *Japanese Political Science Review* 3: 43-65.</li>

<li>Tetsuya Matsubayashi. 2016. "Tohyo Kankyo to Tohyo Ritsu (Polling Stations and Voter Turnout)." *Senkyo Kenkyu (Japanese Journal of Electoral Studies)* 32(1): 47-60.</li>

<li>Yasushi Asako, Tetsuya Matsubayashi, and Michiko Ueda. 2016. "Legislative Term Limits and Government Spending: Theory and Evidence from the United States" *The B.E. Journal of Economic Analysis Policy* 16(3): 1501-1538.</li>

<li>Tony E. Carey Jr., Valerie Martinez-Ebers, Tetsuya Matsubayashi, and Phillip Paolino. 2016. "Eres Amigo o Enemigo? Contextual Determinants of Latinos' Perceived Competition with African-Americans." *Urban Affairs Review* 52(2): 155-181.</li>

<li>Yasushi Asako, Takeshi Iida, Tetsuya Matsubayashi, and Michiko Ueda. 2015. "Dynastic Politicians: Theory and Evidence from Japan." *Japanese Journal of Political Science* 16(1), 5-32.</li>

<li>Tetsuya Matsubayashi. 2015. "Yoron Chosa no Kaitouritsu to Touhyoritsu no Suitei Gosa (Survey Response Rates and Estimation Errors in the Rates of Voter Turnout)." *Rebaiasan (Leviathan)* 57: 96-117.</li>

<li>Regina Branton, Tony E. Carey Jr., Valerie Martinez-Ebers, and Tetsuya Matsubayashi. 2015. "Social Protest and Policy Attitudes: The Case of the 2006 Immigrant Rallies." *American Journal of Political Science* 59(2), 390-402.</li>

<li>Tetsuya Matsubayashi, Michiko Ueda, and Takayoshi Uekami. 2014. "District Population Size and Candidates' Vote-Seeking Strategies: Evidence from Japan." *Journal of Public Opinion, Elections, and Parties* 25(2), 159-177.</li>

<li>Rene Rocha and Tetsuya Matsubayashi. 2014. "The Politics of Race and Voter ID Laws in the States: The Return of Jim Crow?" *Political Research Quarterly* 67(3), 666-679.</li>

<li>Bethany Blackstone, Tetsuya Matsubayashi, and Elizabeth Oldmixon. 2014. "Israeli Attitudes on Synagogue and State." *Politics ¥Religion* 7(1): 122-147.</li>

<li>Tony Carey, Tetsuya Matsubayashi, Regina Branton, and Valerie Martinez-Ebers. 2013. "The Determinants and Political Consequences of Latinos' Perceived Intra-Group Competition." *Politics, Groups, and Identities* 1(3): 311-328.</li>

<li>2013 Rene Rocha and Tetsuya Matsubayashi. 2013. "Latino Immigration and Representation in Local Politics." *Urban Affairs Review* 49(3): 353-380.</li>

<li>Tetsuya Matsubayashi. 2013. "Do Politicians Shape Public Opinion?" *British Journal of Political Science* 43(2): 451-78.</li>

<li>Michiko Ueda and Tetsuya Matsubayashi. 2013. "Fukushi Keizai Seisaku ga Jisatsu ni Ataeru Eikyo: Todoufuken reberu Deta no Bunseki (Welfare and Economic Policies and Suicide Rates: Analysis of Prefecture-level Data in Japan")." *Nihon Keizai Kenkyu (Japan Economic Research)* 69: 96-109.</li>

<li>Tetsuya Matsubayashi and Rene Rocha. 2012. "Racial Diversity and Public Policy in the States." *Political Research Quarterly* 65(3): 600-14.</li>

<li>Tetsuya Matsubayashi and Jun-deh Wu. 2012. "Distributive Politics and Voter Turnout." *Journal of Elections, Public Opinion, ¥Parties* 22(2): 167-85.</li>

<li>Tetsuya Matsubayashi and Michiko Ueda.2012. "Government Partisanship and Human Well-being" *Social Indicators Research* 107(1): 127-48.</li>

<li>Tetsuya Matsubayashi and Michiko Ueda. 2012. "Shichoson Gikai ni okeru Josei no Sannyu (Female Candidates and Municipal Elections in Japan)." *Senkyo Kenkyu (Japanese Journal of Electoral Studies)* 28: 94-109.</li>

<li>Tetsuya Matsubayashi and Michiko Ueda. 2011. "Political Knowledge and the Use of Candidate Race as a Voting Cue." *American Politics Research* 39(2): 380-413.</li>

<li>Tetsuya Matsubayashi. 2011. "Racial Environment and Political Participation." *American Politics Research* 38(3): 471-501.</li>

<li>Takeshi Iida and Tetsuya Matsubayashi. 2010. "Constitutions and Public Support for Welfare Policies." *Social Science Quarterly* 91(1): 42-62.</li>

<li>

</li>

<li>Takeshi Iida, Tetsuya Matsubayashi, and Michiko Ueda. 2010. "Seshu Giin no Jisshou Bunseki (Empirical Analysis of Dynastic Legislators)." *Senkyo Kenkyu (Japanese Journal of Electoral Studies)* 26: 139-53.</li>

<li>Jan Leighley and Tetsuya Matsubayashi. 2009. "The Implications of Class, Race and Ethnicity for Political Networks." *American Politics Research* 37(5): 824-55.</li>

<li>Kim Quaile Hill and Tetsuya Matsubayashi. 2008. "Church Engagement, Religious Values, and Mass-Elite Policy Agenda Agreement in Local Communities." *American Journal of Political Science* 52(3): 570-84.</li>

<li>Tetsuya Matsubayashi. 2007. "Population Size, Local Autonomy, and Support for the Political System." *Social Science Quarterly* 88(3): 830-49.</li>

<li>Kim Quaile Hill and Tetsuya Matsubayashi. 2005. "Civic Engagement and Mass-Elite Policy Agenda Agreement in American Communities." *American Political Science Review* 99(2): 215-24.</li>

<li>Junko Yano, Tetsuya Matsubayashi, and Yoshitaka Nishizawa. 2005. "Jichitaikibo to Jyumin no Seijisanka (City Size and Political Participation)." *Sennkyo Gakkai Kiyo (Reviews of Electoral Studies)* 4: 63-78.</li>

</ol>

### Peer-reviewed Publications in Public Health

<ol reversed>

<li>Tetsuya Matsubayashi, Yumi Ishikawa, Michiko Ueda. 2022. "Economic crisis and mental health during the COVID-19 pandemic in Japan." *Journal of Affective Disorders* 306: 28-31.</li>

<li>Tetsuya Matsubayashi and Takuma Kamada. 2021. "The Great East Japan Earthquake and suicide: The long-term consequences and underlying mechanisms." *Preventive Medicine*</li>

<li>Michiko Ueda, Robert Nordstrom, Tetsuya Matsubayashi. 2021. Suicide and mental health during the COVID-19 pandemic in Japan. *Journal of Public Health* fdab113.</li>

<li>Robert F. Veszteg, Kaori Yamakawa, Tetsuya Matsubayashi, Michiko Ueda. 2021 "Acute stress does not affect economic behavior in the experimental laboratory." *PLoS ONE*16(1): e0244881.</li>

<li>Andrew Stickley, Tetsuya Matsubayashi, Hajime Sueki, Michiko Ueda. 2020. "COVID-19 preventive behaviours among people with anxiety and depressive symptoms: Findings from Japan." *Public Health*</li>

<li>Andrew Stickley, Tetsuya Matsubayashi, Michiko Ueda. 2020. "Loneliness and COVID-19 preventive behaviours among Japanese adults." *Journal of Public Health*.</li>

<li>Michiko Ueda, Andrew Stickley, Hajime Sueki, and Tetsuya Matsubayashi. 2020. "Mental health status of the general population in Japan during the COVID‐19 pandemic." *Psychiatry and Clinical Neurosciences*.</li>

<li>Tetsuya Matsubayashi, Kozue Sekijima, and Michiko Ueda. 2020. "Government Spending, Recession, and Suicide: Evidence from Japan." *BMC Public Health*.</li>

<li>Tetsuya Matsubayashi, Myoung-jae Lee, and Michiko Ueda. 2019. "Higher Risk of Suicide on Milestone Birthdays: Evidence from Japan." *Scientific Reports*.</li>

<li>Shuntaro Ando, Satoshi Usami, Tetsuya Matsubayashi, Michiko Ueda, Shinsuke Koike, Syudo Yamasaki, Shinya Fujikawa,Tsukasa Sasaki, Mariko Hiraiwa-Hasegawa, George Patton, Kiyoto Kasai, Atsushi Nishida. 2019. "Age relative to school class peers and emotional well-being in 10-year-olds." *PLoS ONE* 14(3): e0214359.</li>

<li>Michiko Ueda, Kanako Yoshikawa, and Tetsuya Matsubayashi. 2019. "Suicide by persons with foreign background in Japan." *PLoS ONE* 14(2): e0211867.</li>

<li>Robert A. Fahey, Tetsuya Matsubayashi, and Michiko Ueda. 2018 "Tracking the Werther effect on social media: Emotional responses to prominent suicide deaths on twitter and subsequent increases in suicide." *Social Science & Medicine* 219: 19-29.</li>

<li>Jeremy Boo, Tetsuya Matsubayashi, and Michiko Ueda. "Diurnal variation in suicide timing by age and gender: Evidence from Japan across 41 years." *Journal of Affective Disorders* 243: 366-374.</li>

<li>Tetsuya Matsubayashi and Kanako Yoshikawa. 2018. "Minimum Legal Drinking Age and Youth Health: Evidence from Japan." *Journal of Studies on Alcohol and Drugs* 79: 539-546.</li>

<li>Michiko Ueda, Kota Mori, Tetsuya Matsubayashi, and Yasuyuki Sawada. 2017. "Tweeting celebrity suicides: Users' reaction to prominent suicide deaths on Twitter and subsequent increases in actual suicides." *Social Science & Medicine* 189: 158-166.</li>

<li>Tetsuya Matsubayashi, Michiko Ueda, and Kanako Yoshikawa. 2016. "School and Seasonality in Youth Suicide: Evidence from Japan." *Journal of Epidemiology and Community Health* 70:1122-1127.</li>

<li>Tetsuya Matsubayashi and Michiko Ueda. 2016. "Suicides and Accidents on Birthdays: Evidence from Japan." *Social Science & Medicine* 159: 61-72.</li>

<li>Yong Woon Chung, Sung Jin Kang, Tetsuya Matsubayashi, Yasuyuki Sawada, and Michiko Ueda. 2016. "The Effectiveness of Platform Screen Doors for the Prevention of Subway Suicides in South Korea." *Journal of Affective Disorders* 194: 80-83.</li>

<li>Tetsuya Matsubayashi and Michiko Ueda. 2015. "Relative Age in School and Suicide among Young Individuals in Japan: A Regression Discontinuity Approach." *PLoS ONE* 10(8): e0135349.</li>

<li>Michiko Ueda, Yasuyuki Sawada, and Tetsuya Matsubayashi.2015. "The Effectiveness of Installing Physical Barriers for Preventing Railway Suicides and Accidents: Evidence from Japan." *Journal of Affective Disorders* 178: 1-4.</li>

<li>Tetsuya Matsubayashi, Yasuyuki Sawada, and Michiko Ueda. 2014. "Does the Installation of Blue Lights on Train Platforms Shift Suicide to another Station?: Evidence from Japan." *Journal of Affective Disorders* 169: 57-60.</li>

<li>Tetsuya Matsubayashi and Michiko Ueda. 2014. "Disability and Voting." *Disability and Health Journal* 7: 285-291.</li>

<li>Michiko Ueda, Kota Mori, and Tetsuya Matsubayashi. 2014. "The Effects of Media Reports of Suicides by Well-Known Figures between 1989 and 2010 in Japan." *International Journal of Epidemiology* 43: 623-629.</li>

<li>Tetsuya Matsubayashi, Yasuyuki Sawada, and Michiko Ueda. 2014. "The Effect of Public Awareness Campaigns on Suicides: Evidence from Nagoya, Japan." *Journal of Affective Disorders* 152-154:526-529.</li>

<li>Tetsuya Matsubayashi, Yasuyuki Sawada, and Michiko Ueda. 2013. "Does the Installation of Blue Lights on Train Platforms Prevent Suicide?: A Before-and-After Observational Study from Japan." *Journal of Affective Disorders* 147: 385-88.</li>

<li>Tetsuya Matsubayashi, Yasuyuki Sawada, and Michiko Ueda. 2013. "Natural Disasters and Suicides: Evidence from Japan." *Social Science & Medicine*82: 126-33.</li>

<li>Tetsuya Matsubayashi and Michiko Ueda. 2011. "The Effect of Government Suicide Prevention Programs on Suicide Rates." *Social Science & Medicine*73: 1395-1400.</li>

</ol>

### Books

<ol reversed>

<li>Tetsuya Matsubayashi. 2023. *Nani ga Tohyoritsu wo Takameruka (What, if anything, can be done to increase voter turnout)*. Tokyo: Yuhikaku.</li>

<li>Tetsuya Matsubayashi. 2021. *Seijigaku to Ingasuiron (Political Science and Causal Inference)*. Tokyo: Iwanami Shoten.</li>

<li>Yasuyuki Sawada, Michiko Ueda, and Tetsuya Matsubayashi. 2017. *Economic Analysis of Suicide Prevention.* Springer.</li>

<li>Takeshi Iida, Tetsuya Matsubayashi, and Hanako Ohmura. 2015. *Seiji Kodoron (Political Behavior).* Tokyo: Yuhikaku.</li>

<li>Yasuyuki Sawada, Michiko Ueda, and Tetsuya Matsubayashi. 2013. *Jisatu no nai Shakai wo Mezashite.* Tokyo: Yuhikaku.</li>

</ol>

### Other Publications

<ol reversed>

<li>Tetsuya Matsubayashi. 2023. "Josei Giin ga Fuereba Seiji ha Kawarunoka (Does politics change if there are more women politicians?)." *Yononaka wo Shiru, Kangaeru, Kaeteiku* eds. by Takashi Iida, Ayako Kondo, Yosuke Sunahara, and Satomi Maruyama. Tokyo: Yuhikaku.</li>

<li>Tetsuya Matsubayashi and Masateru Yamatani. 2022. "" *Comparative Public Opinion* eds. by Cameron Anderson and Mathieu Turgeon. Routledge.</li>

<li>Tetsuya Matsubayashi and Michiko Ueda. 2021. "COVID-19 ni yoru Keizai Kiki to Jisatsu." *Japanese Bulletin of Social Psychiatry* 30(2): 142-150.</li>

<li>Tetsuya Matsubayashi. 2016. "Survey Modes and Data Quality." *Electoral Survey Methodology*, eds. by Masaru Kohno and Yoshitaka Nishizawa. New York: Routledge, 13-38.</li>

<li>Tetsuya Matsubayashi. 2016. "No-opinion Options and Survey Responses." *Electoral Survey Methodology*, eds. by Masaru Kohno and Yoshitaka Nishizawa. New York: Routledge, 39-56.</li>

<li>Tetsuya Matsubayashi. 2014. "The Implications of Nonvoting in Japan." *The Annuals of Japanese Political Science Association* I: 175-199.</li>

<li>Tetsuya Matsubayashi and Yoshitaka Nishizawa. 2012. "Estimating the Causal Effect of Survey Modes." *G-COE GLOPE II Working Paper Series* No.55.</li>

<li>Takeshi Iida and Tetsuya Matsubayashi. 2011. "Senkyo Kenkyu niokeru Inga Suiron no Kenkyu Doukou (A Review on Causal Inferences in Electoral Studies)." *Senkyo Kenkyu (Japanese Journal of Electoral Studies)* 27 (1): 101-119.</li>

<li>Tetsuya Matsubayashi. 2009. "Shakaigakuteki Moderu no Hatten (Development of Sociological Model)." *Frontier of Research on Voting Behavior*, eds. by Masahiro Yamada and Takeshi Iida. Tokyo: Ohfu, 15-37.</li>

<li>Jan E. Leighley and Tetsuya Matsubayashi. 2005. "Voter Mobilization." *Guide to Political Campaigns in America*, eds. by Paul S. Herrnson. Washington D.C.: CQ Press, 300-11.</li>

</ol>

### Grants as a Principal Investigator

<ol reversed>

<li>2023-2027. Japan Society for the Promotion of Science (Grant-in-Aid for Scientific Research (S)).</li>

<li>2022-2024. Japan Society for the Promotion of Science (Fund for the Promotion of Joint International Research (Fostering Joint International Research (A))).</li>

<li>2020-2023. Japan Society for the Promotion of Science (Grant-in-Aid for Scientific Research (C)).</li>

<li>2017-2020. Japan Society for the Promotion of Science (Grant-in-Aid for Young Scientists (B)).</li>

<li>2016-2018. The Telecommunications Advancement Foundation.</li>

<li>2016-2018. Japan Center for Economic Research.</li>

<li>2014-2017. Japan Society for the Promotion of Science (Grant-in-Aid for Young Scientists (B)).</li>

<li>2014-2015. Itochube Foundation.</li>

</ol>
